sudo: required
dist: trusty
language: node_js

git:
  depth: 1

cache:
  yarn: true
  directories:
    - ./node_modules

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  - TASK=build
  - TASK=test
  - TASK=lint
  - TASK=site:build

script:
  - npm run $TASK
